name: I find a bug in Archethic Ecosystem.
description: You would like to declare a TECHNICAL or FUNCTIONAL issue and/or send to the Archethic team a proposal of fix.
title: '[Bug]: '
labels: ['Bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the excepted behavior, the actual behavior and could you describe steps to reproduce ("Please tell us exactly how to reproduce the problem you are running into")
    validations:
      required: true
  - type: textarea
    id: proof
    attributes:
      label: Logs / Images
      description: Include the full logs of the commands you are running between the lines with the backticks below. Or screenshots.
    validations:
      required: false
  - type: input
    id: platform
    attributes:
      label: Platform
      description: Could you precise the OS (Android, iOS, Web, MacOS, Linux, Windows, ...), the version or which browser you used.
    validations:
      required: false
  - type: input
    id: version_app
    attributes:
      label: Version of Archethic apps
      description: 
    validations:
      required: false