name: I would like to propose an idea or a new feature.
description: As a contributor, you would like to request or share a new feature 
title: '[Feature]: '
labels: ['Feature']
body:
  - type: input
    id: use_case
    attributes:
      label: Use case
      description: Use case (Please tell us the idea you have)
    validations:
      required: true
  - type: input
    id: detail
    attributes:
      label: Diagram / images vidéos / wireframes / code samples
      description: Include all things you want to explain or show your idea
    validations:
      required: false